# Generated by Django 3.1 on 2020-08-22 15:35

import auctions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20200822_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auction',
            field=models.ManyToManyField(to='auctions.Auction'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='image',
            field=models.ImageField(blank=True, upload_to=auctions.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=auctions.models.get_upload_path),
        ),
    ]
