# Generated by Django 3.1 on 2020-08-22 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20200822_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='auction',
        ),
    ]
