# Generated by Django 3.1 on 2020-08-23 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 23, 13, 44, 54, 352781)),
        ),
        migrations.AddField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 23, 13, 44, 54, 353781)),
        ),
    ]
