# Generated by Django 3.1 on 2020-09-13 08:50

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auto_20200912_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='watch_list',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auction',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 13, 8, 50, 4, 782676, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 13, 8, 50, 4, 784678, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='WatchList',
        ),
    ]
