# Generated by Django 3.1 on 2020-09-17 10:57

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_auto_20200913_1452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-time']},
        ),
        migrations.AddField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.CharField(choices=[('no choice', 'No choice'), ('fashion', 'Fashion'), ('tools', 'Tools'), ('toys', 'Toys'), ('electronics', 'Electronics'), ('home accesories', 'Home accessories'), ('books', 'Books')], default='fashion', max_length=64),
        ),
        migrations.AlterField(
            model_name='auction',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 17, 10, 57, 23, 54846, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='auctions.auction'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 17, 10, 57, 23, 56848, tzinfo=utc)),
        ),
    ]
