# Generated by Django 3.1 on 2020-09-19 11:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_auto_20200917_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 19, 11, 36, 54, 114304, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 19, 11, 36, 54, 115305, tzinfo=utc)),
        ),
    ]
