# Generated by Django 3.1 on 2020-09-19 15:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_auto_20200919_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.CharField(choices=[('no choice', 'No choice'), ('fashion', 'Fashion'), ('tools', 'Tools'), ('toys', 'Toys'), ('electronics', 'Electronics'), ('home accesories', 'Home accessories'), ('books', 'Books')], max_length=64),
        ),
        migrations.AlterField(
            model_name='auction',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 19, 15, 31, 16, 937504, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 19, 15, 31, 16, 938505, tzinfo=utc)),
        ),
    ]
